[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "${SEPOLIA_URL}"
optimism-goerli = "${OPTIMISM_GOERLI_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
optimism-goerli = { key = "${OPT_ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
